### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by Akshay-Vs** [Udaka-Hayerson/myKivyApp#1]
**Everything looks good as a first project**. But please always try to add a readme file. 
 So that others can easily understand what is this is project about.
 It helps a lot when someone is trying to understand what you are doing. 
 hope you understood that.

**Comment by Code-With-juna** [comment]
That's a good suggestion for beginners. Thank you

**Comment by Jim-Huo** [comment]
👍👍👍

**Comment by Erric-Muller** [comment]
Yes, You are right. I'll also try to make my projects more understandable to others
